start_date: '2017-07-10' 
end_date: '2022-07-09'
window_size: 28
horizon_size: 7
target: 'High'
folder_path: '/home/mill-ct-liao/Desktop/share_price_prediction/'
asx200_list: 'ASX200/ASX200_List.xlsx'
asx200_historical_price: 'ASX200/ASX200_Historical_Prices.xlsx'
x_train: 'train_data/X.npy'
y_train: 'train_data/Y.npy'
num_days_5y_companies: 1267